definitions:
  dto.OTPRequest:
    properties:
      phone_number:
        type: string
    type: object
  dto.UserLoginRequest:
    properties:
      password:
        type: string
      phone_number:
        type: string
    type: object
  dto.UserRegisterRequest:
    properties:
      name:
        type: string
      password:
        type: string
      verified_token:
        type: string
    type: object
  dto.VerifyOTPRequest:
    properties:
      otp_code:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /otp/generate:
    post:
      consumes:
      - application/json
      description: Generates an OTP for phone number verification
      parameters:
      - description: Phone Number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.OTPRequest'
      produces:
      - application/json
      responses: {}
      summary: Generate OTP
      tags:
      - OTP
  /otp/verify:
    post:
      consumes:
      - application/json
      description: Verifies the OTP entered by the user
      parameters:
      - description: Phone Number and OTP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyOTPRequest'
      produces:
      - application/json
      responses: {}
      summary: Verify OTP
      tags:
      - OTP
  /users/login:
    post:
      consumes:
      - application/json
      description: login users
      parameters:
      - description: Phone Number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses: {}
      summary: login user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: creating users
      parameters:
      - description: Phone Number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: registering user
      tags:
      - users
  /users/verify-access-token:
    post:
      consumes:
      - application/json
      description: verify access token
      produces:
      - application/json
      responses: {}
      summary: verify access token
      tags:
      - users
swagger: "2.0"
