definitions:
  dto.ForgetPasswordRequest:
    properties:
      phone_number:
        type: string
    type: object
  dto.OTPRequest:
    properties:
      phone_number:
        type: string
    type: object
  dto.PasswordResetRequest:
    properties:
      password:
        type: string
      password_retype:
        type: string
    type: object
  dto.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  dto.UserLoginRequest:
    properties:
      password:
        type: string
      phone_number:
        type: string
    type: object
  dto.UserRegisterRequest:
    properties:
      name:
        type: string
      password:
        type: string
      verified_token:
        type: string
    type: object
  dto.VerifyOTPRequest:
    properties:
      otp_code:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/get-all-users:
    get:
      description: retrieve all users with pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: retrieve all users with pagination
      tags:
      - admin
  /otp/generate:
    post:
      consumes:
      - application/json
      description: Generates an OTP for phone number verification
      parameters:
      - description: Phone Number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.OTPRequest'
      produces:
      - application/json
      responses: {}
      summary: Generate OTP
      tags:
      - OTP
  /otp/verify:
    post:
      consumes:
      - application/json
      description: Verifies the OTP entered by the user
      parameters:
      - description: Phone Number and OTP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyOTPRequest'
      produces:
      - application/json
      responses: {}
      summary: Verify OTP
      tags:
      - OTP
  /users/forget-password:
    post:
      consumes:
      - application/json
      description: get forget password
      parameters:
      - description: Phone number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ForgetPasswordRequest'
      produces:
      - application/json
      responses: {}
      summary: get forget password
      tags:
      - users
  /users/get-access-token-by-refresh-token:
    post:
      consumes:
      - application/json
      description: get access token by refresh token
      parameters:
      - description: Refresh Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenRequest'
      produces:
      - application/json
      responses: {}
      summary: get access token by refresh token
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: login users
      parameters:
      - description: Phone Number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses: {}
      summary: login user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: creating users
      parameters:
      - description: Phone Number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: registering user
      tags:
      - users
  /users/reset-password:
    post:
      consumes:
      - application/json
      description: get reset password
      parameters:
      - description: password and password_retype
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.PasswordResetRequest'
      - description: The encrypted key for password reset
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: get reset password
      tags:
      - users
  /users/verify-access-token:
    post:
      consumes:
      - application/json
      description: verify access token
      produces:
      - application/json
      responses: {}
      summary: verify access token
      tags:
      - users
swagger: "2.0"
